### ISSUE TITLE
KeyError: 'domain' - loads first 10 articles only!

### ISSUE THREAD

**Issue by atmosx** [ryanss/vim-hackernews#1]
Hello,

I cloned the plugin via `pathogen` but when I try to run `HackerNews` I get this error:

```
".hackernews" [New File]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/atma/.vim/bundle/vim-hackernews/plugin/hackernews.py", line 65, in hacker_news
    item['domain'], item['id'])
KeyError: 'domain'
```
My system:
```
~> uname -a
Darwin hilbert.lan 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
~> vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 19 2015 22:49:00)
MacOS X (unix) version
Included patches: 1-258
Compiled by atma@hilbert.lan
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
-cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -DMACOS_X_UNIX  -pipe -Os -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/opt/local/include  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1  
Linking: /usr/bin/clang   -L. -L/opt/local/lib -Wl,-headerpad_max_install_names   -fstack-protector -L/usr/local/lib -L/opt/local/lib  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64 -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework Cocoa  -L/opt/local/lib -llua -L/opt/local/lib -Wl,-headerpad_max_install_names  -fstack-protector  -L/opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation  -L/opt/local/lib -ltcl8.6 -lz -framework CoreFoundation -lruby.2.0.0 -lobjc -L/opt/local/lib   
~> python --version
Python 2.7.9
~> which python
/opt/local/bin/python
~> 
```
It loads the first 10 articles but not more than that.

Thanks for the nice plugin :-)

**Comment by ryanss** [comment]
Thanks for opening this issue. Some "job" type links on the Hacker News front page don't contain a "domain" key on the unofficial API this plugin is using. This has been fixed now.
