### ISSUE TITLE
HackerNews.vim Error: HTTP Request Timeout

### ISSUE THREAD

**Issue by MarkSwanson** [ryanss/vim-hackernews#13]
I tried from a couple of machines/networks.
news.ycombinator.com works in my browser just fine.

Blocked?

**Comment by ryanss** [comment]
The unofficial Hacker News API that this plugin uses is currently not working. It just stopped working a few minutes ago we'll see what happens.

https://github.com/cheeaun/node-hnapi/

**Comment by ubersol** [comment]
I get the following issue starting from this morning:

```
 NORMAL ⮀⮀ [No Name]                                                  ⮂⮂⮂ 0 ⮃ 0 
".hackernews" [New File]                                             
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/212436367/.vim/bundle/vim-hackernews/plugin/hackernews.py", line 
58, in hacker_news
    news1 = json.loads(urllib2.urlopen(API_URL+"/news").read())
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
```
Is the 503 I am getting related to this issue?

**Comment by ryanss** [comment]
Yes, the API has been down a large majority of the day unfortunately.

**Comment by ryanss** [comment]
The API is back up again now.
